version: '3'

services:

  api:
    build:
      context: .
    image: api
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app/api
      - ./test-results:/usr/src/app/test-results
    command: bash -c './wait-for-it.sh db:${MYSQL_PORT} --timeout=60 -- yarn develop'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql-data:
  mysql-logs:
