version: '3'

services:

  api:
    build:
      context: .
    image: api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./test-results:/usr/src/app/test-results
    command: yarn develop

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql-data:
  mysql-logs:
