version: '3'

services:

  api:
    build:
      context: .
    volumes:
      - ./api:/usr/src/app/api
    env_file: .env
    ports:
      - "3000:3000"
    image: api
    depends_on:
      - db
    command: yarn develop

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./dev-dump.sql:/docker-entrypoint-initdb.d/dev-dump.sql
