version: 2

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run:
          name: Copy over .env
          command: cp sample.env .env
      - run:
          name: Run linter
          command: make lint
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  unit_tests:
    machine: true
    steps:
      - checkout
      - run:
          name: Copy over .env
          command: cp sample.env .env
      - run:
          name: 'Run unit tests'
          command: make unit-tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit_tests
