version: 2.1

jobs:
  lint:
    docker: 
      - image: circleci/node:12.18.0
    steps:
      - setup_remote_docker
      - checkout
      - run_make:
          label: Run linter
          target: lint
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

  unit_tests:
    docker: 
      - image: circleci/node:12.18.0
    steps:
      - setup_remote_docker
      - checkout
      - run_make:
          label: Run unit tests
          target: unit-tests
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

commands:
  run_make:
    description: Run a makefile target
    parameters:
      label:
        type: string
        default: Execute make << parameters.target >>
      target:
        type: string
    steps:
      - run:
          name: << parameters.label >>
          command: make << parameters.target >>

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit_tests
