version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run linter
          command: make lint
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

  unit_tests:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - setup_remote_docker
      - checkout
      - run: 
         command: mkdir -p test-results/mocha
      - run:
         name: 'Run unit tests'
         command: make unit-tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit_tests
